### ISSUE TITLE
InvalidEntrypoint Error in M1 Silicon

### ISSUE THREAD

**Issue by GitHubDiom** [cubed-dev/cubed#521]
Hi community,

I encountered an access point error while running an AWS example. Here is the information that I think might help diagnose the issue:

1. I built the container image on a MacBook Pro with an M1 chip.
2. My config.aws is as follows:
```
lithops:
  backend: aws_lambda
  storage: aws_s3
  storage_bucket: lithops-tom-data # I'm not sure if I need to modify this item
  log_level: DEBUG

aws:
  access_key_id: XXXX
  secret_access_key: XXXX

aws_lambda:
  region_name: ap-southeast-1
  execution_role: arn:aws:iam::XXXX:role/lambdaLithopsExecutionRole
  architecture: arm64

aws_s3:
  region_name: ap-southeast-1
  storage_bucket: cubed-jairwu-temp # I have already created this bucket in S3
```
Below is the detailed error information：

(cubed-lithops-aws-examples) ➜  aws git:(main) ✗ lithops runtime deploy -b aws_lambda --memory 2000 --timeout 180 cubed-runtime
```
2024-07-26 15:12:49,927 [INFO] config.py:139 -- Lithops v3.4.1 - Python3.11
2024-07-26 15:12:49,927 [DEBUG] config.py:101 -- Loading configuration from /Users/jairwu/.lithops/config.aws
2024-07-26 15:12:49,935 [DEBUG] config.py:179 -- Loading Serverless backend module: aws_lambda
2024-07-26 15:12:49,964 [DEBUG] config.py:220 -- Loading Storage backend module: aws_s3
2024-07-26 15:12:49,965 [DEBUG] aws_s3.py:36 -- Creating AWS S3 Client
2024-07-26 15:12:50,025 [INFO] aws_s3.py:59 -- S3 client created - Region: ap-southeast-1
2024-07-26 15:12:50,222 [DEBUG] aws_lambda.py:53 -- Creating AWS Lambda client
2024-07-26 15:12:51,304 [INFO] aws_lambda.py:97 -- AWS Lambda client created - Region: ap-southeast-1
2024-07-26 15:12:51,307 [INFO] aws_lambda.py:448 -- Deploying runtime: cubed-runtime - Memory: 2000 Timeout: 180
2024-07-26 15:12:51,935 [DEBUG] aws_lambda.py:165 -- Ok --> function "lithops-worker-7048-341-c2d3f802c2" is active
2024-07-26 15:12:51,936 [DEBUG] aws_lambda.py:516 -- OK --> Created lambda function lithops-worker-7048-341-c2d3f802c2
2024-07-26 15:12:51,936 [DEBUG] aws_lambda.py:700 -- Extracting runtime metadata from: cubed-runtime
2024-07-26 15:12:52,005 [DEBUG] aws_lambda.py:710 -- result: {'errorType': 'Runtime.InvalidEntrypoint', 'errorMessage': 'RequestId: cf368c7f-cd02-400a-8984-5539cf770226 Error: fork/exec /usr/local/bin/python: exec format error'}
Traceback (most recent call last):
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
             ^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/lithops/scripts/cli.py", line 523, in deploy
    runtime_meta = compute_handler.deploy_runtime(runtime_name, runtime_memory, runtime_timeout)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/lithops/serverless/serverless.py", line 84, in deploy_runtime
    return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 531, in deploy_runtime
    runtime_meta = self._generate_runtime_meta(runtime_name, memory)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jairwu/miniforge3/envs/cubed-lithops-aws-examples/lib/python3.11/site-packages/lithops/serverless/backends/aws_lambda/aws_lambda.py", line 715, in _generate_runtime_meta
    raise Exception(f'An error occurred: {result}')
Exception: An error occurred: {'errorType': 'Runtime.InvalidEntrypoint', 'errorMessage': 'RequestId: cf368c7f-cd02-400a-8984-5539cf770226 Error: fork/exec /usr/local/bin/python: exec format error'}
```
I would be very grateful for any help.
Thankyou

**Comment by tomwhite** [comment]
Hi @GitHubDiom - thanks for opening an issue!

> `storage_bucket: lithops-tom-data # I'm not sure if I need to modify this item`

I'm not sure if this is used since you have specified it under `aws_s3` later in the file. Maybe try removing it, or changing to your bucket.

You could try removing `architecture: arm64` since it may not be needed since https://github.com/lithops-cloud/lithops/pull/1298 went in. See also https://github.com/lithops-cloud/lithops/issues/1297, which looks like the same issue.

**Comment by GitHubDiom** [comment]
@tomwhite thanks for the response,

I have removed `storage_bucket` (or change to my bucket) and 'architecture: arm64' under lithops and `aws_lambda` section, respectively. 

But the error is still remained.

**Comment by tomwhite** [comment]
Did you delete the runtime and start from scratch? https://github.com/cubed-dev/cubed/tree/main/examples/lithops/aws#cleaning-up

**Comment by GitHubDiom** [comment]
Thanks for you helping! it works!!

I thought it was okay by delete the image through `docker rmi` and from lambda dashboard.
