### ISSUE TITLE
Help me get running with lithops on aws: ImportError: Install s3fs to access S3

### ISSUE THREAD

**Issue by rabernat** [cubed-dev/cubed#584]
Hi! After some prodding from @TomNicholas, I became curious to get cubed running on lithops on aws. I'm stuck on this error `ImportError: Install s3fs to access S3`

---

Here's my setup.

Cubed version is 0.17.0.

My script (`test.py`)

```python
import cubed
import cubed.array_api as xp
spec = cubed.Spec(
    work_dir="s3://em-cubed-ryan-test",
    allowed_mem=200000000,
    executor_name="lithops",
    executor_options=dict(use_backups=False, runtime="cubed-runtime", runtime_memory=2000)
)
big = xp.ones(shape=(10000, 10000), chunks=(2000, 2000), spec=spec)
xp.sum(big).compute()
```

My process

```bash
lithops runtime build -b aws_lambda -f Dockerfile_aws_lambda cubed-runtime 
lithops runtime deploy -b aws_lambda --memory 2000 --timeout 180 cubed-runtime
python test.py
```

My `.lithops_config`

```yaml
lithops:
   backend: aws_lambda
   storage: aws_s3
   data_limit: false
   log_level: DEBUG
aws:
   region: "us-west-2"
aws_lambda:
   execution_role: "arn:aws:iam::842143331303:role/lithops-execution-role-tmp"
   architecture: x86_64
aws_s3:
   storage_bucket: lithops-us-west-2
```

<details>
<summary> my dockerfile </summary>

```
# Python 3.6
#FROM python:3.6-slim-buster

# Python 3.7
#FROM python:3.7-slim-buster

# Python 3.8
#FROM python:3.8-slim-buster

# Python 3.9
#FROM python:3.9-slim-buster

# Python 3.10
#FROM python:3.10-slim-buster

# Python 3.11
FROM python:3.11-slim-buster

RUN apt-get update \
    # Install aws-lambda-cpp build dependencies
    && apt-get install -y \
      g++ \
      make \
      cmake \
      unzip \
    # cleanup package lists, they are not used anymore in this image
    && rm -rf /var/lib/apt/lists/* \
    && apt-cache search linux-headers-generic

ARG FUNCTION_DIR="/function"

# Copy function code
RUN mkdir -p ${FUNCTION_DIR}

# Update pip
# NB botocore/boto3 are pinned due to https://github.com/boto/boto3/issues/3648
#    using versions from https://github.com/aio-libs/aiobotocore/blob/72b8dd5d7d4ef2f1a49a0ae0c37b47e5280e2070/setup.py
#    due to s3fs dependency
RUN pip install --upgrade --ignore-installed pip wheel six setuptools \
    && pip install --upgrade --no-cache-dir --ignore-installed \
        awslambdaric \
        botocore==1.29.76 \
        boto3==1.26.76 \
        redis \
        httplib2 \
        requests \
        numpy \
        scipy \
        pandas \
        pika \
        kafka-python \
        cloudpickle \
        ps-mem \
        tblib

# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

# Add Lithops
COPY lithops_lambda.zip ${FUNCTION_DIR}
RUN unzip lithops_lambda.zip \
    && rm lithops_lambda.zip \
    && mkdir handler \
    && touch handler/__init__.py \
    && mv entry_point.py handler/

# Put your dependencies here, using RUN pip install... or RUN apt install...

RUN pip install \
        cubed \
        s3fs

ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD [ "handler.entry_point.lambda_handler" ]
```
</details>

<details>
<summary>Full log output</summary>

```
% python test.py                                                                
2024-09-26 15:31:46,811 [INFO] config.py:139 -- Lithops v3.5.0 - Python3.11
2024-09-26 15:31:46,811 [DEBUG] config.py:101 -- Loading configuration from /Users/rabernat/gh/earth-mover/cubed-test/.lithops_config
2024-09-26 15:31:46,812 [DEBUG] config.py:179 -- Loading Serverless backend module: aws_lambda
2024-09-26 15:31:46,893 [DEBUG] config.py:219 -- Loading Storage backend module: aws_s3
2024-09-26 15:31:46,895 [DEBUG] aws_s3.py:36 -- Creating AWS S3 Client
2024-09-26 15:31:47,006 [INFO] aws_s3.py:59 -- S3 client created - Region: us-west-2
2024-09-26 15:31:47,296 [DEBUG] aws_lambda.py:53 -- Creating AWS Lambda client
2024-09-26 15:31:47,494 [INFO] aws_lambda.py:97 -- AWS Lambda client created - Region: us-west-2
2024-09-26 15:31:47,496 [DEBUG] invokers.py:105 -- ExecutorID cd7fb9-0 - Invoker initialized. Max workers: 1000
2024-09-26 15:31:47,496 [DEBUG] invokers.py:307 -- ExecutorID cd7fb9-0 - Serverless invoker created
2024-09-26 15:31:47,496 [DEBUG] executors.py:151 -- Function executor for aws_lambda created with ID: cd7fb9-0
2024-09-26 15:31:47,496 [INFO] invokers.py:119 -- ExecutorID cd7fb9-0 | JobID M000 - Selected Runtime: cubed-runtime - 2000MB
2024-09-26 15:31:47,496 [DEBUG] storage.py:476 -- Runtime metadata found in local disk cache
2024-09-26 15:31:47,497 [DEBUG] job.py:242 -- ExecutorID cd7fb9-0 | JobID M000 - Serializing function and data
2024-09-26 15:31:47,499 [DEBUG] serialize.py:75 -- Referenced Modules: zarr, cubed, numpy, functools, donfig
2024-09-26 15:31:47,499 [DEBUG] module_dependency.py:109 -- Module 'zarr' is already installed in the runtime, skipping
2024-09-26 15:31:47,499 [DEBUG] module_dependency.py:109 -- Module 'cubed' is already installed in the runtime, skipping
2024-09-26 15:31:47,499 [DEBUG] module_dependency.py:109 -- Module 'numpy' is already installed in the runtime, skipping
2024-09-26 15:31:47,499 [DEBUG] module_dependency.py:109 -- Module 'functools' is already installed in the runtime, skipping
2024-09-26 15:31:47,499 [DEBUG] module_dependency.py:109 -- Module 'donfig' is already installed in the runtime, skipping
2024-09-26 15:31:47,499 [DEBUG] serialize.py:120 -- Modules to transmit: None
2024-09-26 15:31:47,499 [DEBUG] job.py:276 -- ExecutorID cd7fb9-0 | JobID M000 - Uploading function and modules to the storage backend
2024-09-26 15:31:47,678 [DEBUG] aws_s3.py:106 -- PUT Object lithops.jobs/cd7fb9-0/53e9eb33cd35c2fc648ab90ecb4a1bdd.func.pickle - Size: 1.2KiB - OK
2024-09-26 15:31:47,678 [DEBUG] job.py:316 -- ExecutorID cd7fb9-0 | JobID M000 - Data per activation is < 8.0KiB. Passing data through invocation payload
2024-09-26 15:31:47,678 [INFO] invokers.py:186 -- ExecutorID cd7fb9-0 | JobID M000 - Starting function invocation: <lambda>() - Total: 3 activations
2024-09-26 15:31:47,678 [DEBUG] invokers.py:212 -- ExecutorID cd7fb9-0 | JobID M000 - Worker processes: 1 - Chunksize: 1
2024-09-26 15:31:47,678 [DEBUG] invokers.py:316 -- ExecutorID cd7fb9-0 - Async invoker 0 started
2024-09-26 15:31:47,678 [DEBUG] invokers.py:316 -- ExecutorID cd7fb9-0 - Async invoker 1 started
2024-09-26 15:31:47,679 [DEBUG] invokers.py:445 -- ExecutorID cd7fb9-0 | JobID M000 - Free workers: 1000 - Going to run 3 activations in 3 workers
2024-09-26 15:31:47,682 [INFO] invokers.py:225 -- ExecutorID cd7fb9-0 | JobID M000 - View execution logs at /private/var/folders/kl/7rfdrpx96bb0rhbnl5l2dnkw0000gn/T/lithops-rabernat/logs/cd7fb9-0-M000.log
2024-09-26 15:31:47,682 [DEBUG] monitor.py:429 -- ExecutorID cd7fb9-0 - Starting Storage job monitor
2024-09-26 15:31:47,682 [INFO] wait.py:105 -- ExecutorID cd7fb9-0 - Waiting for any of 3 function activations to complete
2024-09-26 15:31:48,008 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M000 - Calls 00002 invoked (0.327s) - Activation ID: f9f19f6e-a1b9-40f1-8e96-623d4ea3dcd2
2024-09-26 15:31:48,009 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M000 - Calls 00000 invoked (0.330s) - Activation ID: 9c9687af-556b-4c26-9a3f-1860bd6ecf33
2024-09-26 15:31:48,015 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M000 - Calls 00001 invoked (0.335s) - Activation ID: 17fb0854-92ff-4554-89c5-5b541c24e66e
2024-09-26 15:31:50,159 [DEBUG] monitor.py:144 -- ExecutorID cd7fb9-0 - Pending: 3 - Running: 0 - Done: 0
2024-09-26 15:31:52,363 [DEBUG] monitor.py:144 -- ExecutorID cd7fb9-0 - Pending: 0 - Running: 3 - Done: 0
2024-09-26 15:32:03,429 [DEBUG] monitor.py:144 -- ExecutorID cd7fb9-0 - Pending: 0 - Running: 0 - Done: 3
2024-09-26 15:32:03,430 [DEBUG] monitor.py:457 -- ExecutorID cd7fb9-0 - Storage job monitor finished
2024-09-26 15:32:03,736 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M000 - Got status from call 00001 - Activation ID: 17fb0854-92ff-4554-89c5-5b541c24e66e - Time: 9.92 seconds
2024-09-26 15:32:03,737 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M000 - Got status from call 00000 - Activation ID: 9c9687af-556b-4c26-9a3f-1860bd6ecf33 - Time: 9.97 seconds
2024-09-26 15:32:03,737 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M000 - Got status from call 00002 - Activation ID: f9f19f6e-a1b9-40f1-8e96-623d4ea3dcd2 - Time: 9.87 seconds
2024-09-26 15:32:03,737 [INFO] invokers.py:119 -- ExecutorID cd7fb9-0 | JobID M001 - Selected Runtime: cubed-runtime - 2000MB
2024-09-26 15:32:03,738 [DEBUG] storage.py:472 -- Runtime metadata found in local memory cache
2024-09-26 15:32:03,738 [DEBUG] job.py:242 -- ExecutorID cd7fb9-0 | JobID M001 - Serializing function and data
2024-09-26 15:32:03,743 [DEBUG] serialize.py:75 -- Referenced Modules: functools, cubed
2024-09-26 15:32:03,743 [DEBUG] module_dependency.py:109 -- Module 'functools' is already installed in the runtime, skipping
2024-09-26 15:32:03,743 [DEBUG] module_dependency.py:109 -- Module 'cubed' is already installed in the runtime, skipping
2024-09-26 15:32:03,743 [DEBUG] serialize.py:120 -- Modules to transmit: None
2024-09-26 15:32:03,743 [DEBUG] job.py:276 -- ExecutorID cd7fb9-0 | JobID M001 - Uploading function and modules to the storage backend
2024-09-26 15:32:03,910 [DEBUG] aws_s3.py:106 -- PUT Object lithops.jobs/cd7fb9-0/d7315149b9fbcf0fff2f2e7492b5bf04.func.pickle - Size: 5.8KiB - OK
2024-09-26 15:32:03,910 [DEBUG] job.py:316 -- ExecutorID cd7fb9-0 | JobID M001 - Data per activation is < 8.0KiB. Passing data through invocation payload
2024-09-26 15:32:03,910 [INFO] invokers.py:186 -- ExecutorID cd7fb9-0 | JobID M001 - Starting function invocation: <lambda>() - Total: 9 activations
2024-09-26 15:32:03,911 [DEBUG] invokers.py:212 -- ExecutorID cd7fb9-0 | JobID M001 - Worker processes: 1 - Chunksize: 1
2024-09-26 15:32:03,911 [DEBUG] invokers.py:445 -- ExecutorID cd7fb9-0 | JobID M001 - Free workers: 997 - Going to run 9 activations in 9 workers
2024-09-26 15:32:03,925 [INFO] invokers.py:225 -- ExecutorID cd7fb9-0 | JobID M001 - View execution logs at /private/var/folders/kl/7rfdrpx96bb0rhbnl5l2dnkw0000gn/T/lithops-rabernat/logs/cd7fb9-0-M001.log
2024-09-26 15:32:03,928 [DEBUG] monitor.py:429 -- ExecutorID cd7fb9-0 - Starting Storage job monitor
2024-09-26 15:32:03,928 [INFO] wait.py:105 -- ExecutorID cd7fb9-0 - Waiting for any of 9 function activations to complete
2024-09-26 15:32:04,038 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M001 - Calls 00000 invoked (0.127s) - Activation ID: dacb8a0c-91fd-4d46-bb45-d39c82afed69
2024-09-26 15:32:04,039 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M001 - Calls 00002 invoked (0.126s) - Activation ID: bedbbe48-6be2-4294-8f26-04d67f5cbd6c
2024-09-26 15:32:04,058 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M001 - Calls 00001 invoked (0.146s) - Activation ID: 196e9b80-4131-4ad4-b25d-1bad48a921c6
2024-09-26 15:32:04,180 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M001 - Calls 00004 invoked (0.265s) - Activation ID: 9d55eafc-d3d2-4892-95c2-af25ac83b288
2024-09-26 15:32:04,186 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M001 - Calls 00007 invoked (0.268s) - Activation ID: 604d9786-a948-458e-add4-e4dc76edf417
2024-09-26 15:32:04,187 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M001 - Calls 00003 invoked (0.273s) - Activation ID: c413fbc2-117a-4913-a338-617182750dc6
2024-09-26 15:32:04,192 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M001 - Calls 00005 invoked (0.277s) - Activation ID: c66aa511-3d14-4146-a5d9-93f8406ac867
2024-09-26 15:32:04,193 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M001 - Calls 00008 invoked (0.273s) - Activation ID: fdf05c07-c467-498f-8134-f0d1598720f3
2024-09-26 15:32:04,203 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M001 - Calls 00006 invoked (0.286s) - Activation ID: 314ac40c-445f-4a9b-bf0f-497c7090de71
2024-09-26 15:32:06,394 [DEBUG] monitor.py:144 -- ExecutorID cd7fb9-0 - Pending: 1 - Running: 5 - Done: 3
2024-09-26 15:32:06,938 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M001 - Got status from call 00000 - Activation ID: dacb8a0c-91fd-4d46-bb45-d39c82afed69 - Time: 1.04 seconds
2024-09-26 15:32:06,938 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M001 - Got status from call 00002 - Activation ID: bedbbe48-6be2-4294-8f26-04d67f5cbd6c - Time: 1.02 seconds
2024-09-26 15:32:06,939 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M001 - Got status from call 00001 - Activation ID: 196e9b80-4131-4ad4-b25d-1bad48a921c6 - Time: 1.04 seconds
2024-09-26 15:32:06,940 [INFO] wait.py:105 -- ExecutorID cd7fb9-0 - Waiting for any of 6 function activations to complete
2024-09-26 15:32:06,987 [DEBUG] monitor.py:144 -- ExecutorID cd7fb9-0 - Pending: 0 - Running: 2 - Done: 7
2024-09-26 15:32:07,581 [DEBUG] monitor.py:144 -- ExecutorID cd7fb9-0 - Pending: 0 - Running: 0 - Done: 9
2024-09-26 15:32:07,581 [DEBUG] monitor.py:457 -- ExecutorID cd7fb9-0 - Storage job monitor finished
2024-09-26 15:32:07,946 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M001 - Got status from call 00006 - Activation ID: 314ac40c-445f-4a9b-bf0f-497c7090de71 - Time: 1.21 seconds
2024-09-26 15:32:07,946 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M001 - Got status from call 00004 - Activation ID: 9d55eafc-d3d2-4892-95c2-af25ac83b288 - Time: 1.09 seconds
2024-09-26 15:32:07,946 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M001 - Got status from call 00003 - Activation ID: c413fbc2-117a-4913-a338-617182750dc6 - Time: 1.16 seconds
2024-09-26 15:32:07,947 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M001 - Got status from call 00005 - Activation ID: c66aa511-3d14-4146-a5d9-93f8406ac867 - Time: 1.13 seconds
2024-09-26 15:32:07,947 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M001 - Got status from call 00007 - Activation ID: 604d9786-a948-458e-add4-e4dc76edf417 - Time: 1.30 seconds
2024-09-26 15:32:07,948 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M001 - Got status from call 00008 - Activation ID: fdf05c07-c467-498f-8134-f0d1598720f3 - Time: 1.14 seconds
2024-09-26 15:32:07,948 [INFO] invokers.py:119 -- ExecutorID cd7fb9-0 | JobID M002 - Selected Runtime: cubed-runtime - 2000MB
2024-09-26 15:32:07,948 [DEBUG] storage.py:472 -- Runtime metadata found in local memory cache
2024-09-26 15:32:07,949 [DEBUG] job.py:242 -- ExecutorID cd7fb9-0 | JobID M002 - Serializing function and data
2024-09-26 15:32:07,952 [DEBUG] serialize.py:75 -- Referenced Modules: functools, cubed
2024-09-26 15:32:07,952 [DEBUG] module_dependency.py:109 -- Module 'functools' is already installed in the runtime, skipping
2024-09-26 15:32:07,952 [DEBUG] module_dependency.py:109 -- Module 'cubed' is already installed in the runtime, skipping
2024-09-26 15:32:07,952 [DEBUG] serialize.py:120 -- Modules to transmit: None
2024-09-26 15:32:07,952 [DEBUG] job.py:276 -- ExecutorID cd7fb9-0 | JobID M002 - Uploading function and modules to the storage backend
2024-09-26 15:32:08,266 [DEBUG] aws_s3.py:106 -- PUT Object lithops.jobs/cd7fb9-0/67be6b03fcad0bb20ee38edd8cc12574.func.pickle - Size: 7.4KiB - OK
2024-09-26 15:32:08,266 [DEBUG] job.py:316 -- ExecutorID cd7fb9-0 | JobID M002 - Data per activation is < 8.0KiB. Passing data through invocation payload
2024-09-26 15:32:08,266 [INFO] invokers.py:186 -- ExecutorID cd7fb9-0 | JobID M002 - Starting function invocation: <lambda>() - Total: 4 activations
2024-09-26 15:32:08,266 [DEBUG] invokers.py:212 -- ExecutorID cd7fb9-0 | JobID M002 - Worker processes: 1 - Chunksize: 1
2024-09-26 15:32:08,266 [DEBUG] invokers.py:445 -- ExecutorID cd7fb9-0 | JobID M002 - Free workers: 988 - Going to run 4 activations in 4 workers
2024-09-26 15:32:08,267 [INFO] invokers.py:225 -- ExecutorID cd7fb9-0 | JobID M002 - View execution logs at /private/var/folders/kl/7rfdrpx96bb0rhbnl5l2dnkw0000gn/T/lithops-rabernat/logs/cd7fb9-0-M002.log
2024-09-26 15:32:08,267 [DEBUG] monitor.py:429 -- ExecutorID cd7fb9-0 - Starting Storage job monitor
2024-09-26 15:32:08,268 [INFO] wait.py:105 -- ExecutorID cd7fb9-0 - Waiting for any of 4 function activations to complete
2024-09-26 15:32:08,354 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M002 - Calls 00000 invoked (0.087s) - Activation ID: 8a574c6f-ece6-4369-a9f5-0bd6037fe4bb
2024-09-26 15:32:08,364 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M002 - Calls 00001 invoked (0.096s) - Activation ID: 1adca5e9-1bde-4c78-9c1d-edb4cb884292
2024-09-26 15:32:08,372 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M002 - Calls 00003 invoked (0.103s) - Activation ID: 85b8f4a8-bf84-46a7-9f50-af7c8a31c8cb
2024-09-26 15:32:08,373 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M002 - Calls 00002 invoked (0.104s) - Activation ID: 64161ac1-1a88-4dc0-838d-51e1017aca04
2024-09-26 15:32:10,490 [DEBUG] monitor.py:144 -- ExecutorID cd7fb9-0 - Pending: 0 - Running: 0 - Done: 4
2024-09-26 15:32:10,490 [DEBUG] monitor.py:457 -- ExecutorID cd7fb9-0 - Storage job monitor finished
2024-09-26 15:32:11,280 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M002 - Got status from call 00000 - Activation ID: 8a574c6f-ece6-4369-a9f5-0bd6037fe4bb - Time: 1.14 seconds
2024-09-26 15:32:11,284 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M002 - Got status from call 00002 - Activation ID: 64161ac1-1a88-4dc0-838d-51e1017aca04 - Time: 0.92 seconds
2024-09-26 15:32:11,285 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M002 - Got status from call 00001 - Activation ID: 1adca5e9-1bde-4c78-9c1d-edb4cb884292 - Time: 1.02 seconds
2024-09-26 15:32:11,285 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M002 - Got status from call 00003 - Activation ID: 85b8f4a8-bf84-46a7-9f50-af7c8a31c8cb - Time: 0.98 seconds
2024-09-26 15:32:11,286 [INFO] invokers.py:119 -- ExecutorID cd7fb9-0 | JobID M003 - Selected Runtime: cubed-runtime - 2000MB
2024-09-26 15:32:11,286 [DEBUG] storage.py:472 -- Runtime metadata found in local memory cache
2024-09-26 15:32:11,286 [DEBUG] job.py:242 -- ExecutorID cd7fb9-0 | JobID M003 - Serializing function and data
2024-09-26 15:32:11,292 [DEBUG] serialize.py:75 -- Referenced Modules: functools, cubed
2024-09-26 15:32:11,292 [DEBUG] module_dependency.py:109 -- Module 'functools' is already installed in the runtime, skipping
2024-09-26 15:32:11,292 [DEBUG] module_dependency.py:109 -- Module 'cubed' is already installed in the runtime, skipping
2024-09-26 15:32:11,292 [DEBUG] serialize.py:120 -- Modules to transmit: None
2024-09-26 15:32:11,292 [DEBUG] job.py:276 -- ExecutorID cd7fb9-0 | JobID M003 - Uploading function and modules to the storage backend
2024-09-26 15:32:11,622 [DEBUG] aws_s3.py:106 -- PUT Object lithops.jobs/cd7fb9-0/1c28e7f84033f9e6610309f6b5f95c52.func.pickle - Size: 16.5KiB - OK
2024-09-26 15:32:11,623 [DEBUG] job.py:316 -- ExecutorID cd7fb9-0 | JobID M003 - Data per activation is < 8.0KiB. Passing data through invocation payload
2024-09-26 15:32:11,623 [INFO] invokers.py:186 -- ExecutorID cd7fb9-0 | JobID M003 - Starting function invocation: <lambda>() - Total: 1 activations
2024-09-26 15:32:11,623 [DEBUG] invokers.py:212 -- ExecutorID cd7fb9-0 | JobID M003 - Worker processes: 1 - Chunksize: 1
2024-09-26 15:32:11,623 [DEBUG] invokers.py:445 -- ExecutorID cd7fb9-0 | JobID M003 - Free workers: 984 - Going to run 1 activations in 1 workers
2024-09-26 15:32:11,623 [INFO] invokers.py:225 -- ExecutorID cd7fb9-0 | JobID M003 - View execution logs at /private/var/folders/kl/7rfdrpx96bb0rhbnl5l2dnkw0000gn/T/lithops-rabernat/logs/cd7fb9-0-M003.log
2024-09-26 15:32:11,624 [DEBUG] monitor.py:429 -- ExecutorID cd7fb9-0 - Starting Storage job monitor
2024-09-26 15:32:11,624 [INFO] wait.py:105 -- ExecutorID cd7fb9-0 - Waiting for any of 1 function activations to complete
2024-09-26 15:32:11,849 [DEBUG] invokers.py:388 -- ExecutorID cd7fb9-0 | JobID M003 - Calls 00000 invoked (0.225s) - Activation ID: 2315801b-d49f-4204-a75f-a5879a234f6f
2024-09-26 15:32:13,845 [DEBUG] monitor.py:144 -- ExecutorID cd7fb9-0 - Pending: 0 - Running: 0 - Done: 1
2024-09-26 15:32:13,845 [DEBUG] monitor.py:457 -- ExecutorID cd7fb9-0 - Storage job monitor finished
2024-09-26 15:32:14,634 [DEBUG] future.py:229 -- ExecutorID cd7fb9-0 | JobID M003 - Got status from call 00000 - Activation ID: 2315801b-d49f-4204-a75f-a5879a234f6f - Time: 1.11 seconds
2024-09-26 15:32:14,635 [DEBUG] invokers.py:343 -- ExecutorID cd7fb9-0 - Stopping async invokers
2024-09-26 15:32:14,635 [DEBUG] invokers.py:330 -- ExecutorID cd7fb9-0 - Async invoker 0 finished
2024-09-26 15:32:14,635 [DEBUG] invokers.py:330 -- ExecutorID cd7fb9-0 - Async invoker 1 finished
Traceback (most recent call last):
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/fsspec/registry.py", line 242, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/fsspec/registry.py", line 277, in _import_class
    mod = importlib.import_module(mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 's3fs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rabernat/gh/earth-mover/cubed-test/test.py", line 10, in <module>
    xp.sum(big).compute()
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/cubed/core/array.py", line 153, in compute
    result = compute(
             ^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/cubed/core/array.py", line 294, in compute
    return tuple(a._read_stored() for a in arrays)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/cubed/core/array.py", line 294, in <genexpr>
    return tuple(a._read_stored() for a in arrays)
                 ^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/cubed/core/array.py", line 119, in _read_stored
    return numpy_array_to_backend_array(self.zarray[...])
                                        ^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/cubed/core/array.py", line 58, in zarray
    return open_if_lazy_zarr_array(self._zarray)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/cubed/storage/zarr.py", line 113, in open_if_lazy_zarr_array
    return array.open() if isinstance(array, LazyZarrArray) else array
           ^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/cubed/storage/zarr.py", line 76, in open
    return open_backend_array(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/cubed/storage/backend.py", line 44, in open_backend_array
    return open_func(
           ^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/cubed/storage/backends/zarr_python.py", line 23, in open_zarr_array
    return zarr.open_array(
           ^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/zarr/creation.py", line 592, in open_array
    store = normalize_store_arg(
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/zarr/storage.py", line 201, in normalize_store_arg
    return normalize_store(store, storage_options, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/zarr/storage.py", line 171, in _normalize_store_arg_v2
    return FSStore(store, mode=mode, **(storage_options or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/zarr/storage.py", line 1384, in __init__
    self.map = fsspec.get_mapper(url, **{**mapper_options, **storage_options})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/fsspec/mapping.py", line 249, in get_mapper
    fs, urlpath = url_to_fs(url, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/fsspec/core.py", line 396, in url_to_fs
    chain = _un_chain(url, kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/fsspec/core.py", line 344, in _un_chain
    cls = get_filesystem_class(protocol)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rabernat/mambaforge/envs/cubed311/lib/python3.11/site-packages/fsspec/registry.py", line 244, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: Install s3fs to access S3
```
</details>

I'm confused why s3fs is not accessiable as it is clearly in the environment.

Any help you can provide would be much appreciated!

**Comment by rabernat** [comment]
And it was simple, just had to install s3fs in my _local_ environment!

Sorry for the noise. Hopefully this is useful documentation for someone.

**Comment by tomwhite** [comment]
> Sorry for the noise. Hopefully this is useful documentation for someone.

Glad you got it working!
